"""Generate a default config.yaml file for Sift.

When Sift is installed via pip, users won't have a config.yaml in their
working directory. This module generates one with sensible defaults so
they can easily customize settings without editing code.
"""

from __future__ import annotations

import os


DEFAULT_CONFIG_YAML = """\
# Sift Configuration
# Generated by: sift init
# Edit this file to customize scraping, clustering, and LLM settings.

sources:
    disabled_sources:
        - "reddit"
    default_sources:
        - "g2"
        - "app_store"
        - "play_store"
        - "youtube"
        - "hacker_news"
        - "github_issues"
        - "product_hunt"
        - "stack_overflow"
        - "dev_to"
        - "support_forums"
        - "changelogs"
        - "discord_exports"
        - "linkedin_comments"

relevance:
    enabled: true
    threshold: 0.45
    min_items_before_relaxing: 3

products: {}

reddit:
    subreddits:
        - "SaaS"
        - "productivity"
        - "startups"
        - "software"
        - "AskReddit"
    search_sort: "relevance"
    max_posts: 30
    max_comments_per_post: 15
    target_rate_per_minute: 80
    praw_ratelimit_seconds: 300
    subreddit_delay: 2.0

g2:
    request_delay: 2.5
    max_pages: 5
    user_agent_rotation: true
    max_requests_per_minute: 12
    backoff_base: 2.0
    max_backoff: 60.0
    max_retries: 3
    jitter_range: [0.5, 1.5]
    use_playwright_fallback: true

app_store:
    app_ids: {}
    countries: ["us"]
    max_pages: 1
    max_items: 50
    request_delay: 1.0
    max_requests_per_minute: 30

play_store:
    package_names: {}
    countries: ["us"]
    languages: ["en"]
    max_items: 50
    request_delay: 1.0
    max_requests_per_minute: 20

youtube:
    video_ids: {}
    max_videos: 5
    max_comments_per_video: 50
    order: "relevance"

hacker_news:
    max_items: 50
    tags: "comment,story"
    request_delay: 1.0
    max_requests_per_minute: 30

github_issues:
    repos: {}
    max_items: 50
    request_delay: 1.0
    max_requests_per_minute: 30

product_hunt:
    slugs: {}
    max_items: 50
    request_delay: 2.0
    max_requests_per_minute: 20
    use_playwright_fallback: true

stack_overflow:
    sites: ["stackoverflow"]
    max_items: 50
    request_delay: 1.0
    max_requests_per_minute: 20

dev_to:
    max_items: 50
    request_delay: 1.0
    max_requests_per_minute: 20

support_forums:
    search_urls: []
    max_items: 50
    request_delay: 1.0
    max_requests_per_minute: 20

changelogs:
    urls: {}
    search_urls: []
    max_items: 50
    request_delay: 1.0
    max_requests_per_minute: 20

discord_exports:
    paths: []
    urls: []
    max_items: 100

linkedin_comments:
    paths: []
    urls: []
    max_items: 100

clustering:
    embedding_model: "all-MiniLM-L12-v2"
    umap_n_neighbors: 15
    umap_n_components: 5
    hdbscan_min_cluster_size: 3
    hdbscan_min_samples: 1

llm:
    model: "deepseek-v4-flash"
    temperature: 0.3
    max_tokens: 8000

logging:
    level: "ERROR"
    format: "%(asctime)s [%(name)s] %(levelname)s: %(message)s"
"""


def generate_default_config(path: str = "config.yaml") -> bool:
    """Write the default config.yaml to the given path.

    Returns True if the file was created, False if it already existed
    (existing files are never overwritten).
    """
    if os.path.exists(path):
        return False

    with open(path, "w") as f:
        f.write(DEFAULT_CONFIG_YAML)

    return True
